### ISSUE TITLE
Export w/o input

### ISSUE THREAD

**Issue by hexaclue** [HIHIQY1/pride-overlay#2]
A user should be able to export the image without an input image. This would mean that the exported image is just a pride flag.

## Requirements:
- [x] A message above the export button saying that it is just the pride flag without any input.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Wouldn't a simple solution be to just disable the check for an image? It'd just be a transparent input image by default when there's no uploaded images, since overlaying images already work like this when transparency is disabled, though I haven't looked into the source of the project yey
