### ISSUE TITLE
Select multiple flags

### ISSUE THREAD

**Issue by hexaclue** [HIHIQY1/pride-overlay#3]
Users should be able to select multiple flags, to put besides each other.

## Requirements:
- [x] Selector, just like the current flag selector, but with an "➕ Add another flag" button besides the selector or underneath the list of flags.
- [x] Rendering them the right way

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Could also provide multiple layouts instead of just side by side? For example, for 3 flags you could allow for them to be aligned... Triangularly? I think? Though that'd get harder as more flags are added, but could be done with some math probably
